server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_booking
    username: postgres
    password: Nitin456#*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true

application:
  name: hospital-booking-backend
